### ISSUE TITLE
What's the source of drug data?

### ISSUE THREAD

**Issue by Wiley-Z** [SeonghwanSeo/DeepDL#1]
Hi! I recognized that the number of samples in drug datasets 'worlddrug' (2.8k+) and 'fda' (1.4k+), which you used in this research, is much larger than DrugBank database approved part (2.7k+). And it seems that there is no reference for both datasets. Are they your in-house datasets? Or could you please offer the approach to get they? Thank you!

**Comment by SeonghwanSeo** [comment]
I get both dataset from ZINC15 Database ( [https://zinc15.docking.org/substances/subsets/](https://zinc15.docking.org/substances/subsets/) )
