### ISSUE TITLE
An error will occur in the c_to_i function when 'X' in smiles

### ISSUE THREAD

**Issue by computbiol** [SeonghwanSeo/DeepDL#2]
An error will occur in the c_to_i function when 'X' in smiles. For example, 'CC(C)N(C)C(C)C[Xe][Re]'. 

Ref: https://github.com/SeonghwanSeo/DeepDL/blob/b23915ce66e77a3b36fefebbc9578152cad897b6/src/dataset.py#L43

**Comment by SeonghwanSeo** [comment]
We trained the model with drug molecules and only use the character contained in the SMILES of drug molecules.
Since there were no Xe atoms in the data set, the character 'X' was not be considered.

You can train model with 'Xe' by changing source code. (https://github.com/SeonghwanSeo/DeepDL/blob/master/src/utils/data_utils/smiles_utils.py)

**Comment by computbiol** [comment]
But your pretrain seems to be using pubchem data.

**Comment by computbiol** [comment]
> We trained the model with drug molecules and only use the character contained in the SMILES of drug molecules. Since there were no Xe atoms in the data set, the character 'X' was not be considered.
> 
> You can train model with 'Xe' by changing source code. (https://github.com/SeonghwanSeo/DeepDL/blob/master/src/utils/data_utils/smiles_utils.py)

There may be some problems with my code environment. I would like to ask if you can provide a download of the already-trained model. Thank you very much.

**Comment by SeonghwanSeo** [comment]
> But your pretrain seems to be using pubchem data.

I just checked the data set and found that molecules containing Xe atoms were missing during a random selection of 10M molecules out of the total Pubchem molecules.
I recommend you to filter out the molecule containing Xe.

**Comment by SeonghwanSeo** [comment]
I'll add a Google Drive link soon.

**Comment by SeonghwanSeo** [comment]
I found the pre-trained model files are already uploaded. (https://github.com/SeonghwanSeo/DeepDL/tree/master/test/result/rnn_pubchem_worlddrug)
If there is any problem, download the save file from following google drive link. I upload our main RNN model in there.
https://drive.google.com/drive/folders/1H3G1Y8ynyly485QtrqyWnUfseSzHaC6I?usp=sharing
