### ISSUE TITLE
drug data source

### ISSUE THREAD

**Issue by sjchasel** [SeonghwanSeo/DeepDL#5]
Hi! You said that you download the drug data from ZINC15(https://zinc15.docking.org/substances/subsets/), are they world-not-fda and fda subsets? In ZINC15, world-not-fda subset only has 2068 molecules, fda subset only has 1379 molecules, which is less than that you use.
And according to your paper, you remove molecules from worlddrug with a similarity greater than 0.8 to fda, so is the number of molecules in the original worlddrug dataset larger?

**Comment by SeonghwanSeo** [comment]
Dear @sjchasel,

The number in the subset section is not updated. If you click on the link of each subset, you will find more molecules.
(link: https://zinc15.docking.org/substances/subsets/world-not-fda/) 
Now, 4288 molecules are included in world-not-fda set.

FDA dataset is a subset of Worlddrug dataset. (Worlddrug set includes the drug which is not only approved by FDA but also approved by other governments)

Best,
Seonghwan Seo.
