### ISSUE TITLE
About drug data preprocessing

### ISSUE THREAD

**Issue by ABOWLofFish** [SeonghwanSeo/DeepDL#6]
Dear @SeonghwanSeo,

Hi. I hope this message finds you well. Would you mind providing the script to process the original Worlddrug data into training data? I have been trying to divide the data based on the threshold setting in papar but unable to obtain the correct number of molecules. Your assistance might be really helpful.

Thank You.

Best Regards.

**Comment by SeonghwanSeo** [comment]
Dear @ABOWLofFish ,

Sorry for delayed response.

While I lost the processing code, but I think following code can be useful.
(This code is written by recent RDKit version, so please change this according to your rdkit version)

```python
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem

fpgen = AllChem.GetMorganGenerator(radius=2)

with open( "./data/test/fda.smi") as f:
    test_smi_list = [ln.strip() for ln in f.readlines()]
test_fp_list = [fpgen.GetFingerprint(Chem.MolFromSmiles(smi)) for smi in test_smi_list]

with open("./data/train/worlddrug.smi") as f:
    train_smi_list = [ln.strip() for ln in f.readlines()]
print("before filtering", len(train_smi_list))

filtered = []
for smi in train_smi_list:
    fp = fpgen.GetFingerprint(Chem.MolFromSmiles(smi))
    sim = DataStructs.BulkTanimotoSimilarity(fp, test_fp_list)
    if max(sim) < 0.8:
        filtered.append(smi)
    else:
        print(smi)
print("after filtering", len(filtered))
```

**Comment by SeonghwanSeo** [comment]
Since World Drugs and FDA in ZINC20 might be expanded after 2021, you would not get the correct number in the paper.
However, if you used MorganFingerprint with radius of 2 and nBits of 2048, it is same to our data processing.

**Comment by ABOWLofFish** [comment]
Thank you very much for your help!  Perhaps you still preserve the raw data of World Drugs and FDA in ZINC20 from the version prior to 2021? If so, would it be convenient for you to provide it?

**Comment by SeonghwanSeo** [comment]
Unfortunately, I didn't save the raw file of 2021's version. (The uploaded FDA drug file is 2021's one (except our basic filtering rule))

If you need the raw file of WorldDrug for fair comparison for benchmark study, I think it is okay to use updated WorldDrug database with uploaded FDA file in Github. I think there are few difference in terms of chemical diversity.

**Comment by ABOWLofFish** [comment]
It's Alright. Anyway thanks for your patience.
Wish you a pleasant day:)
